### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by hbg99** [corbindavenport/nexus-tools#15]
It didn't work.
When I try to install the drivers it writes:

ADB=/usr/bin/adb: Command not found.
FASTBOOT=/usr/bin/fastboot: Command not found.
UDEV=/etc/udev/rules.d/51-android.rules: Command not found.
Illegal variable name.

Moreover, I precise I'm on an iMac 32bits on mac osX Lion, and the first command didn't work at all, so I had to use the second one.

**Comment by corbindavenport** [comment]
Try using the new Nexus Tools 2.6 release (with the new install command) and see if you have the same problem.
On May 19, 2015 8:39 AM, hbg99 <notifications@github.com> wrote:It didn't work.
When I try to install the drivers it writes:

ADB=/usr/bin/adb: Command not found.
FASTBOOT=/usr/bin/fastboot: Command not found.
UDEV=/etc/udev/rules.d/51-android.rules: Command not found.
Illegal variable name.

Moreover, I precise I'm on an iMac 32bits on mac osX Lion, and the first command didn't work at all, so I had to use the second one;
