### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by fedmeloni** [corbindavenport/nexus-tools#17]
I try to install on OS X, with both the instructions, but without result.

This is what terminal says:

[INFO] Nexus Tools 2.6.3
[INFO] Please enter sudo password for install.
[ OK ] Sudo access granted.
[INFO] Downloading ADB for Mac OS X...
[EROR] Download failed.
[INFO] Downloading Fastboot for Mac OS X...
[EROR] Download failed.
expr: syntax error
[INFO] Making ADB and Fastboot executable...
[EROR] chmod: /usr/bin/adb: No such file or directory
[EROR] chmod: /usr/bin/fastboot: No such file or directory
[EROR] Install failed

**Comment by corbindavenport** [comment]
Are you using Mac OS X El Capitan? It's been reported not to work on that version, I'm trying to figure out why.

**Comment by fedmeloni** [comment]
Yes, I m on El Capitan. Thanks
