### ISSUE TITLE
Raspi 2 support?

### ISSUE THREAD

**Issue by cclamp** [corbindavenport/nexus-tools#18]
Any support for Raspi 2? armv7l. Scripts says my architecture couldn't be detected. I'm running the Ubuntu Mate port. https://ubuntu-mate.org/raspberry-pi/

Thanks
C

**Comment by corbindavenport** [comment]
What does the command 'arch' output?

**Comment by cclamp** [comment]
armv7l

As an experiment I swapped the armv6 portion of your code to look for that string "armv7l" instead, and it downloaded adb, and it seemed to run and work correctly, but it was very very old. 1.0.29 or something is what showed up. It did say they were out of date and very old, any chance of them being updated?

I'm looking at getting this going a couple different ways, hopefully something works out, but your installer script is pretty neat:)

Thanks
C

**Comment by corbindavenport** [comment]
As far as I can tell, no one has compiled more recent ARM binaries that I can use. If someone recompiled the latest version for ARM, I would happily include it in Nexus Tools :)

**Comment by corbindavenport** [comment]
Issue fixed in Nexus Tools 2.6.6.
