### ISSUE TITLE
Update adb and fastboot binaries

### ISSUE THREAD

**Issue by iceandfire** [corbindavenport/nexus-tools#19]
Please update the adb and fastboot binaries for Linux (Intel) PCs. Current binaries are out of date and can't be used to flash factory images on Nexus devices. Example: Nexus 6.

Log:
sending 'system' (1737204 KB)...
(bootloader) Data size exceeds download buffer
FAILED (remote failure)
finished. total time: 0.795s

**Comment by corbindavenport** [comment]
I just updated Nexus Tools to 2.7, with the latest ADB/Fastboot binaries. It should work now.
