### ISSUE TITLE
el capitan - suggested rootless fix didn't work

### ISSUE THREAD

**Issue by chenks** [corbindavenport/nexus-tools#21]
the el capitan "rootlessToggler" didn't work for me.
are there any other solutions other than having to edit the script?

**Comment by corbindavenport** [comment]
What is the output of Nexus Tools after running rootlessToggler?

**Comment by chenks** [comment]
same output as before i used rootlessToggler.
in the end i just booted to recovery mode and disabled SIP there (csrutil disable), and got it working.

the rootlessToggler didn't appear to do anything (but it does say on the website that it was only tested on Beta 1), it's possible that the tool doesn't work on the final release.

**Comment by corbindavenport** [comment]
From some research it seems the command to change the rootless boot flag was disabled a while ago (which is probably that RootlessTrigger used), now the only method that works is booting into recovery. Thanks for letting me know, I added it to the [El Capitan wiki page](https://github.com/corbindavenport/nexus-tools/wiki/Fix-for-Mac-OS-X-10.11-(El-Capitan)).

**Comment by mrmatt** [comment]
Just install to /usr/local/bin rather than /usr/bin -- that's what it is there for.  No permissions issues and no need to change overall system security.

**Comment by corbindavenport** [comment]
@mrmatt I don't have access to an El Capitan Mac, but I'm fairly sure /usr/local/bin is still blocked by Rootless. It at least requires sudo access on my OS X 10.9 Mac.

**Comment by mrmatt** [comment]
Yes, you need SUDO to write to /usr/local/bin/ but it isn't completely
forbidden & blocked like /usr/bin/ is by rootless.

**Comment by corbindavenport** [comment]
Thanks for the feedback everyone, Nexus Tools 2.8 should fix El Capitan compatibility. I'll leave this issue open until someone on El Capitan reports it working.

**Comment by corbindavenport** [comment]
I was able to verify Nexus Tools 2.8 works on El Capitan, issue closed.
