### ISSUE TITLE
Download Failed on iMac (2013) 10.10.5

### ISSUE THREAD

**Issue by kinged007** [corbindavenport/nexus-tools#28]
Hello, I have been through the XDA thread, and cant seem to find anyone else having the same issue... I dont have El Capitan so not sure what the problem on my end could be?
I type : bash <(curl -s https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh)
to install, and this is the output:
Tests-iMac:~ joshua$ bash <(curl -s https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh)
[INFO] Nexus Tools 2.8
[INFO] Please enter sudo password for install.
Password:
[ OK ] Sudo access granted.
[INFO] Downloading ADB for Mac OS X...
[EROR] Download failed.
[INFO] Downloading Fastboot for Mac OS X...
[EROR] Download failed.
[INFO] Making ADB and Fastboot executable...
[EROR] chmod: /usr/local/bin/adb: No such file or directory
[EROR] chmod: /usr/local/bin/fastboot: No such file or directory
[INFO] Adding /usr/local/bin to PATH...
[EROR] Install failed

Please can you help me? What should I try? I dont have any firewalls running, and I uninstalled Little Snitch just in case, same results.

Many thanks
Josh

**Comment by corbindavenport** [comment]
I have a friend with an El Capitan Mac I can ask to try the script on. If
he has the same problem, it's probably a 10.11-specific bug I need to look
at.

Corbin

Corbin

**Comment by corbindavenport** [comment]
My friend reported it was working fine on his El Capitan Mac, are you sure you typed the correct sudo password?

**Comment by kinged007** [comment]
Hi Corbin, yes of course.
ᐧ
