### ISSUE TITLE
Nexus Tools install failed on Asus 13" chromebook 

### ISSUE THREAD

**Issue by dustinjefferies** [corbindavenport/nexus-tools#29]
Hi 
  Trying to install ADB and fastboot on Asus 2015 chromebook. Below is the logging output. Any help? 

chronos@localhost / $ bash <(curl -s https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh)
[INFO] Nexus Tools 3.1
/dev/fd/63: line 97: gcc: command not found
[INFO] Please enter sudo password for install.
[ OK ] Sudo access granted.
/dev/fd/63: line 110: gcc: command not found
[INFO] Linux is detected but dpkg is either not working or not installing, now attempting dirty removal.
[INFO] Linux is detected but dpkg is either not working or not installing, now attempting dirty removal.
[INFO] Downloading ADB for Linux [Intel CPU]...
[ OK ] Download succeeded.
[INFO] Downloading Fastboot for Linux [Intel CPU]...
[ OK ] Download succeeded.
[INFO] Downloading udev list...
[EROR] Download failed.
[EROR] chmod: cannot access ‘/etc/udev/rules.d/51-android.rules’: No such file or directory
[EROR] chown: cannot access ‘/etc/udev/rules.d/51-android.rules’: No such file or directory
[ OK ] Marked ADB as executable.
[ OK ] Marked ADB as executable.
[INFO] Adding /home/chronos/user/.nexustools to $PATH...
[EROR] Install failed.
[EROR] Report bugs at: github.com/corbindavenport/nexus-tools/issues
[EROR] Report the following information in the bug report:
[EROR] OS: Linux
[EROR] ARCH: x86_64

**Comment by corbindavenport** [comment]
Nexus Tools stopped supporting Chrome OS a while back because I wasn't able to get it working with newer Chrome OS updates. Sorry :/

**Comment by dustinjefferies** [comment]
OK! I was able to get it working on the ubuntu partition of my Chromebook anyway. Thanks.
