### ISSUE TITLE
If zsh is the active terminal, PATHs are not added

### ISSUE THREAD

**Issue by Ardakilic** [corbindavenport/nexus-tools#31]
I'm using zsh + [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) instead of bash as default terminal, and after I install nexus tools, because `export PATH=$PATH:~/.nexustools` is not added to `.zshrc`, I cannot run `adb` or `fastboot` directly. 

So my suggestion is to check this file and append to it if exists.

Thanks in advance,

**Comment by corbindavenport** [comment]
Thanks for reporting that, I'll try to get zsh on some linux VM soon and make sure it works.

**Comment by vooze** [comment]
Same thing for fish shell. Had to revert to bash and install.

But otherwise thank you!

**Comment by corbindavenport** [comment]
This is now fixed in the `dev` branch, and should arrive in the master branch soon.

**Comment by Ardakilic** [comment]
@corbindavenport sorry for the bump. I tried installing on a fresh macOS, but sadly it didn't add the folder to my PATH. I've created a new pull request #48 regarding this.

**Comment by corbindavenport** [comment]
Merged.
