### ISSUE TITLE
Acer C720 Chromos adb "permission denied"

### ISSUE THREAD

**Issue by ProfessorKaos64** [corbindavenport/nexus-tools#32]
This did nothing after entering `shell`:

`bash <(curl -s https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh)`

So I downloading the raw script and ran it after making my / partition rw:

```
wget https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh
sudo chmod +x install.sh
./install.sh
```

This installed the tools fine, but I had to do this, per the readme below. I don't think nexus tools is properly added to path. Any new tab with shell doesn't show it.

```
PATH=~/.nexustools:$PATH
```

This piece of code seems to do nothing to ~/.bash_profile:

```
echo "[INFO] Adding $HOME/.nexustools to \$PATH..."
PATH=~/.nexustools:$PATH echo 'export PATH=$PATH:~/.nexustools' >> ~/.bash_profile
```

Running that last command as a normal user adds it fine.  Once I added this to the path, everything worked.

So... I would suggest this be added to the readme for ChromeOS folks

>If you  have read/write access to your file system first, or bash execute will not work, in which you must run 'bash install.sh'. Otherwise, './install.sh' will work fine.

>wget https://raw.githubusercontent.com/corbindavenport/nexus-tools/master/install.sh
sudo chmod +x install.sh
./install.sh

> Run the following command if ~/.bash_profile is unaltered:

>PATH=~/.nexustools:$PATH echo 'export PATH=$PATH:~/.nexustools' >> ~/.bash_profile

**Comment by corbindavenport** [comment]
Do you know the commands/steps required to make the file system RW?

**Comment by ProfessorKaos64** [comment]
See: https://sites.google.com/site/cr48ite/getting-technical/remove-rootfs-verification-make-read-write

However, do note that I had to use `--partitions 2` instead of `--partitions 4`. You can double check this by ommitting the partitions argument, as it should warning/exit with the proper command. This does require [developer mode](https://www.cnet.com/how-to/how-to-enable-developer-mode-on-a-chromebook/), as commonly known for things like crouton.

**Comment by corbindavenport** [comment]
Thanks, I've created a [wiki page](https://github.com/corbindavenport/nexus-tools/wiki/Chrome-OS-Help) with the instructions and linked to it in the readme.
