### ISSUE TITLE
Fastboot too old error while flashing Android 8.1 Oreo

### ISSUE THREAD

**Issue by iceandfire** [corbindavenport/nexus-tools#38]
This is what I get when trying to flash Android 8.1 Oreo on my Nexus 6P. I'm using a MacBook running MacOS High Sierra. 

fastboot too old
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by cameronaaron** [comment]
I actually have a fix for this I think will fix after finals

**Comment by iceandfire** [comment]
Thank you!

**Comment by iceandfire** [comment]
Well it still gives me the same error while flashing angler-opm3.171019.013 factory image. I tried uninstalling and reinstalling the adb/fastboot.

**Comment by iceandfire** [comment]
I replaced the fastboot binary in the .nexustools folder with the fastboot found in the 8th comment here:
https://issuetracker.google.com/issues/64292422#comment8

Flashed the latest Android 8.1 factory image on the Nexus 6P using it successfully. Confirmed to be working fine on MacOS High Sierra 10.13.2.

**Comment by corbindavenport** [comment]
The PR from @cameronaaron only includes the Mac binaries, I'll try to update the script with binaries for Mac and Linux sometime today.

**Comment by corbindavenport** [comment]
This was fixed months ago, closing.
