### ISSUE TITLE
Reopened: Fastboot too old error while flashing Android 8.1 Oreo

### ISSUE THREAD

**Issue by noyb666** [corbindavenport/nexus-tools#43]
Because this problem still persists, and I'm not the only one, I reopened this issue...

No, my fastboot is not too old:

apt install fastboot
Reading package lists... Done
Building dependency tree      
Reading state information... Done
fastboot is already the newest version (1:7.0.0+r33-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

But still I get this message and am not able to proceed with flashing.

angler-opm6.171019.030.h1# ./flash-all.sh
fastboot too old

I had the same issue some 2 month before, got always this error message. Tried a few days later again, everything went smoothly.

Now it's like deja vu all over again...

**Comment by corbindavenport** [comment]
Can you try using the development version of the Nexus Tools installer?

```
bash <(curl -s https://raw.githubusercontent.com/corbindavenport/nexus-tools/dev/install.sh)
```

**Comment by noyb666** [comment]
Yes, that worked, thanks. 
I had to remove adb and fastboot first manually but then it worked as it should...
Very strange, since I got this error, later it worked and now the error came back. So the only thing that is sure is that the output: fastboot too old is nonsense, because it was always up to date...

**Comment by corbindavenport** [comment]
Nexus Tools now grabs ADB, Fastboot, and other tools straight from Google. If you're still having issues as of when this comment is posted, then it's a bug with the tools themselves.
