### ISSUE TITLE
OS not detected

### ISSUE THREAD

**Issue by kon4ri** [corbindavenport/nexus-tools#49]
![image](https://user-images.githubusercontent.com/65653365/82427201-1b490e80-9acc-11ea-947f-6188c5288913.png)

**Comment by corbindavenport** [comment]
Thanks for the bug report, I'll fire up my Chromebook and see what's up.

**Comment by corbindavenport** [comment]
@kon4ri Are you using an ARM Chromebook? AArch64 should be 64-bit ARM.

**Comment by kon4ri** [comment]
ooh, maybe you can help me (and this other guy). We have Lenovo C330
chromebooks but the ADB debugging option is unavailable. Does that mean we
can't sideload apks?

**Comment by corbindavenport** [comment]
Yeah, Google only provides binary files for x86 platforms on its website, so I can only support x86-based hardware with Nexus Tools. I'll update the script to correct this.

I don't personally have an ARM Chromebook to test, but [Debian claims to have ARM binaries for ADB](https://packages.debian.org/sid/adb), so you can try running this command:

```
sudo apt install adb
```
