### ISSUE TITLE
Custom path additions seemingly overwritten after install

### ISSUE THREAD

**Issue by DJankauskas** [corbindavenport/nexus-tools#71]
On macOS Ventura on an Apple Silicon device, after running the nexus-tools install script, my custom path configuration seems to have been overwritten. Other applications not in the default path, like homebrew, are no longer usable without using their full paths. 

Is this reversible? Also, this seems like it should be fixed.

**Comment by corbindavenport** [comment]
I can't duplicate this on macOS Ventura 13.3.1 on an M1 Mac Mini, running a fresh install doesn't break Homebrew or anything else. Can you give me the results of the two below commands?

```
echo $PATH
cat ~/.zshrc
```

Nexus Tools's changes should be reversable by opening ~/.zshrc in a text editor (like with the `open -a TextEdit ~/.zshrc` command) and removing the line for Nexus Tools.

**Comment by DJankauskas** [comment]
After re-running the script and doing a clean install, I can no longer replicate the issue. (Printing out PATH, some tools I hadn't reinstalled after running nexus-tools were still in the PATH, and I was able to use them properly.). Not sure what happened before, but since I can't replicate the bug either, might be worth closing the issue.
